// Regenerates src/generated/jszip-min.ts from the installed jszip dependency.
// Run `pnpm codegen` after bumping jszip and commit the result — the kit must
// never resolve jszip from node_modules at runtime (bundler safety).
import { createRequire } from 'node:module'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const jszipPath = require.resolve('jszip/dist/jszip.min.js')
const jszipPkg = require('jszip/package.json')
const source = readFileSync(jszipPath, 'utf8')

const outDir = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'generated',
)
mkdirSync(outDir, { recursive: true })

const banner = `// GENERATED by scripts/embed-jszip.mjs — do not edit.
// Embedded jszip runtime for browser-side unpack payloads (bundler-safe:
// no node_modules resolution at runtime).
export const JSZIP_VERSION = ${JSON.stringify(jszipPkg.version)};
export const JSZIP_MIN_JS: string = ${JSON.stringify(source)};
`

writeFileSync(join(outDir, 'jszip-min.ts'), banner)
console.log(`embedded jszip ${jszipPkg.version} (${source.length} bytes)`)
